apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  storage:
    size: 1Gi
    storageClass: nfs-csi
  
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.5-0.4.3
