apiVersion: apps/v1
kind: Deployment

metadata:
  name: immich-server

spec:
  selector:
    matchLabels:
      app: immich-server

  template:
    metadata:
      labels:
        app: immich-server

    spec:
      volumes:
        - name: photos
          persistentVolumeClaim:
            claimName: photos
        - name: external-photos
          nfs:
            server: 192.168.1.210
            path: /volume1/Photos
            readOnly: true

      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:v1.139.4

          ports:
            - name: http
              containerPort: 2283

          volumeMounts:
            - name: photos
              mountPath: /usr/src/app/upload
            - name: external-photos
              mountPath: /photos

          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-app
                  key: uri
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_HOSTNAME
              value: "redis.immich.svc.cluster.local"
            - name: IMMICH_PORT
              value: "2283"
            - name: MACHINE_LEARNING_HTTP_KEEPALIVE_TIMEOUT_S
              value: "0"
