apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich

resources:
  - namespace.yaml
  - persistent_volume_claim.yaml
  - database_cluster.yaml
  - database.yaml
  - redis.yaml
  - service_redis.yaml
  - immich_server.yaml
  - service_immich_server.yaml
  - ingress.yaml
  - immich_ml.yaml
  - service_immich_ml.yaml

images:
  - name: ghcr.io/immich-app/immich-server
    newTag: v2.6.3@sha256:0cc1f82953d9598eb9e9dd11cbde1f50fe54f9c46c4506b089e8ad7bfc9d1f0c
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: v2.6.3@sha256:33b17015c3d14f2565e9b8cd36b48a70027b14b5cd20da7fbfff21a370b0309c
  - name: ghcr.io/valkey-io/valkey
    newTag: 9.0.3-alpine@sha256:84c96f47ebe197e635cd3ddbe3ab74e8bdf783cf3befbfb1c36387275c1cd5d5
