apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich

resources:
  - namespace.yaml
  - persistent_volume_claim.yaml
  - database_cluster.yaml
  - database.yaml
  - redis.yaml
  - service_redis.yaml
  - immich_server.yaml
  - service_immich_server.yaml
  - immich_worker.yaml
  - scaler_worker.yaml
  - ingress.yaml
  - immich_ml.yaml
  - service_immich_ml.yaml

images:
  - name: ghcr.io/immich-app/immich-server
    newTag: v3.2.4@sha256:d317916b28090c33eb36b308464ea391f8b7df1d850fcfea227a39ec879718c2
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: v3.2.4@sha256:e16c2f166a8174901959fdf85e2e4c7bd1ebc4b37e0b6655de97c41408a260c4
  - name: ghcr.io/valkey-io/valkey
    newTag: 9.1.2-alpine@sha256:a174b894902bd3367e330d47cc2054367dc4917701776aaf336f41d83b65ec7a
