apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich

resources:
  - namespace.yaml
  - persistent_volume_claim.yaml
  - database_cluster.yaml
  - database.yaml
  - redis.yaml
  - service_redis.yaml
  - immich_server.yaml
  - service_immich_server.yaml
  - ingress.yaml
  - immich_ml.yaml
  - service_immich_ml.yaml

images:
  - name: ghcr.io/immich-app/immich-server
    newTag: v2.7.3@sha256:00cd2d57e4d9310a4aeac3c23f249af1eadbc1802746e1178589ef0a49374cef
  - name: ghcr.io/immich-app/immich-machine-learning
    newTag: v2.7.3@sha256:ccea091ea02086bb9a4712497a6db945a10548f7817101fa18e9b20fdb4f746f
  - name: ghcr.io/valkey-io/valkey
    newTag: 9.0.3-alpine@sha256:84c96f47ebe197e635cd3ddbe3ab74e8bdf783cf3befbfb1c36387275c1cd5d5
