apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - dashboard_auth.yaml
  - ingressroute_traefik_dashboard.yaml
  - middleware_https_redirect.yaml
  - middleware_traefik_dashboard_auth.yaml
