apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver

metadata:
  name: ops

spec:
  type: github
  events:
    - ping
    - push
  secretRef:
    name: ops-webhook-secret
  resources:
    - kind: GitRepository
      name: flux-system
