apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.yaml
  - deployment.yaml
  - image_repository.yaml
  - image_policy.yaml
  - persistent_volume_claim.yaml
images:
  - name: ghcr.io/nint8835/planespotter
    newTag: main-38a20e7-20260520-180120 # {"$imagepolicy": "flux-system:planespotter:tag"}
    digest: sha256:874ba074a85da16739e4318b92385ecec08b36280a1c39e47aec0e05bfd21e1c # {"$imagepolicy": "flux-system:planespotter:digest"}
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: override-namespace
      namespace: planespotter
    unsetOnly: true
