apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.yaml
  - deployment.yaml
  - image_repository.yaml
  - image_policy.yaml
  - persistent_volume_claim.yaml
images:
  - name: ghcr.io/nint8835/planespotter
    newTag: main-39706ad-20260509-194416 # {"$imagepolicy": "flux-system:planespotter:tag"}
    digest: sha256:7ff97979e164cb361acbef2e0f402ca5d52b4830e49eddca4aa3c163fe685ab0 # {"$imagepolicy": "flux-system:planespotter:digest"}
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: override-namespace
      namespace: planespotter
    unsetOnly: true
