apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.yaml
  - deployment.yaml
  - image_repository.yaml
  - image_policy.yaml
  - persistent_volume_claim.yaml
images:
  - name: ghcr.io/nint8835/planespotter
    newTag: main-6ceb633-20260503-145301 # {"$imagepolicy": "flux-system:planespotter:tag"}
    digest: sha256:3e9dc9f00164719943821eabc9eb4528c00369104ea6349aa5d7d082ee72317e # {"$imagepolicy": "flux-system:planespotter:digest"}
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: override-namespace
      namespace: planespotter
    unsetOnly: true
