apiVersion: v1
kind: Secret
metadata:
    name: secrets
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:8MfCaJiRYklKRjVJoaThUATbOvfiqtqYgu0jUJBDfLLonF1JIF5M4VJCe5yBhtS+i8liVC2V5Vv+uwx+r0cIPohkUCF3/8u3k4REsoAj5N3Vhc7npv8ZUXlNwjRPCjxNiHcRc6D/Rdyg/sNNdkXY55sNq+coaEBa/Y4C3Xj2Iv8=,iv:PPJpkQ6qbz6Zat2BVeJ35r7mogR5srailDzk60m7nUo=,tag:oR7GFH0p7MxjJXIma1ugTA==,type:str]
    DISCORD_WEBHOOK_THREAD_ID: ENC[AES256_GCM,data:Pq6wZ39qWQtgjH2wh5MNy/oeEg==,iv:32fnf5j5xfucXQtkvcVtIfm3VXKHL6hJQ8UkWu1SV64=,tag:x1RMejLLgPs3kF3Ap55fyg==,type:str]
sops:
    age:
        - recipient: age1rmn09vuxjzh9wmx4hj8zz72ckgaa3psdzsaglj3all5k7gp5wqpsvvtmz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVlFoak0rU0Q2UUdTMTFD
            TWZaY1pMUzNPOENTT2UrNjMyNzlNRDNacFg0CkNWTC85cERNR2s2SlFzNU1QY3pZ
            NkN6R1YxaXU5MGF5dyt2MTF1Y2hyYXMKLS0tIHg1OUlsd1lQRTNKZDN4cWJNeUY0
            THNWZGxNQjA5L3BKZ2d1T2tHcW9kNTAKdQY9y/M4BEUdNbmHPHoKNRa3O+sHK96v
            GtXd0aU8iLntQSMLoduorxmMuxJUScEp0C8rCofCWctwaskdGcJquQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T01:25:09Z"
    mac: ENC[AES256_GCM,data:h/ulAkxmt1ClQY6NfmI3P0eIOEcY6llhfyj+YbvBWAX/CezDYW/aD/CunIa+w5BxBN6UU1CtyvjvXHemqnyeyQx/U3k5vznU1ev4HQdAbilkJsgtvopl0hjvPXVxy3dxHnCas3XtshXsKi63n9qdacVNGSKOj0vVZtHf24uNwAc=,iv:8BCYBVuweBKmZCXEfoR9QVtdVZk7LT10d/txI3wrb2c=,tag:t+r9XNIGhUBykkNLYwKjoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
