apiVersion: apps/v1
kind: Deployment

metadata:
  name: scribe

spec:
  replicas: 1

  selector:
    matchLabels:
      app: scribe

  template:
    metadata:
      labels:
        app: scribe

    spec:
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: database

      containers:
        - name: scribe
          image: ghcr.io/nint8835/scribe:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8000
              name: http
              protocol: TCP

          env:
            - name: SCRIBE_DB_PATH
              value: /data/quotes.sqlite
            - name: SCRIBE_CALLBACK_URL
              value: https://scribe.bootleg.technology/auth/callback
            - name: SCRIBE_MENTION_CACHE_PATH
              value: /data/mentions.json

          envFrom:
            - secretRef:
                name: secrets
              prefix: SCRIBE_

          volumeMounts:
            - mountPath: /data
              name: database

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            # TODO: Make true once the container image runs as non-root
            runAsNonRoot: false
            seccompProfile:
              type: RuntimeDefault
