apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy

metadata:
  name: scribe
  namespace: flux-system

spec:
  imageRepositoryRef:
    name: scribe
  filterTags:
    pattern: '^main-[[:xdigit:]]{7,}-(?P<ts>\d{8}-\d{6})$'
    extract: '$ts'
  policy:
    alphabetical:
      order: asc
  digestReflectionPolicy: IfNotPresent
