apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - persistent_volume_claim.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - image_repository.yaml
  - image_policy.yaml
images:
  - name: ghcr.io/nint8835/scribe
    newTag: main-f27dbbd-20260719-193426 # {"$imagepolicy": "flux-system:scribe:tag"}
    digest: sha256:2a2f20f3d2cba677f1e0d818d25c27613678e18bce93c3aa3af5b98926d37528 # {"$imagepolicy": "flux-system:scribe:digest"}
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: override-namespace
      namespace: scribe
    unsetOnly: true
