apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - persistent_volume_claim.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - image_repository.yaml
  - image_policy.yaml
images:
  - name: ghcr.io/nint8835/scribe
    newTag: main-5b84645-20260629-195846 # {"$imagepolicy": "flux-system:scribe:tag"}
    digest: sha256:3a438ffe4085e09d85f63fa34e8fd2d043ad25f53d774224e0da1fca93fa36af # {"$imagepolicy": "flux-system:scribe:digest"}
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: override-namespace
      namespace: scribe
    unsetOnly: true
