apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - persistent_volume_claim.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - image_repository.yaml
  - image_policy.yaml
images:
  - name: ghcr.io/nint8835/scribe
    newTag: main-8c33209-20260718-191055 # {"$imagepolicy": "flux-system:scribe:tag"}
    digest: sha256:fbfed683102dbff4c8ba9caf3a39325af6cdb021f59aea1b275dc411db33f021 # {"$imagepolicy": "flux-system:scribe:digest"}
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: override-namespace
      namespace: scribe
    unsetOnly: true
