apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - persistent_volume_claim.yaml
  - deployment.yaml
  - image_repository.yaml
  - image_policy.yaml
images:
  - name: ghcr.io/nint8835/ntv-webcam-scraper
    newTag: main-20d0208-20260726-112142 # {"$imagepolicy": "flux-system:ntv-webcam-scraper:tag"}
    digest: sha256:432e94abeba323dbfd93e646a5242ef210b6ea23dde275e9aa9fbcfb7651a60f # {"$imagepolicy": "flux-system:ntv-webcam-scraper:digest"}
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: override-namespace
      namespace: ntv-webcam-scraper
    unsetOnly: true
