apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflare-ddns
  namespace: flux-system
spec:
  interval: 1h0m0s
  sourceRef:
    kind: ExternalArtifact
    name: cloudflare-ddns
  path: './'
  prune: true
  timeout: 5m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cloudflare-ddns
      namespace: cloudflare-ddns
  decryption:
    provider: sops
