apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: interruption-spotter
  namespace: flux-system
spec:
  interval: 1h0m0s
  dependsOn:
    - name: traefik-configs
    - name: cert-manager-configs
    - name: nfs-csi
  sourceRef:
    kind: ExternalArtifact
    name: interruption-spotter
  path: './'
  prune: true
  timeout: 5m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: interruption-spotter
      namespace: interruption-spotter
