apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ntv-webcam-scraper
  namespace: flux-system
spec:
  interval: 1h0m0s
  dependsOn:
    - name: nfs-csi
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: 'flux/apps/ntv-webcam-scraper'
  prune: true
  timeout: 5m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: ntv-webcam-scraper
      namespace: ntv-webcam-scraper
