apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pkg-nit-so
  namespace: flux-system
spec:
  interval: 1h0m0s
  dependsOn:
    - name: traefik-configs
    - name: cert-manager-configs
  sourceRef:
    kind: ExternalArtifact
    name: pkg-nit-so
  path: './pkg-nit-so'
  prune: true
  timeout: 5m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: dieppe
      namespace: pkg-nit-so
