apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: shopkeeper
  namespace: flux-system
spec:
  interval: 1h0m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: 'flux/apps/shopkeeper'
  prune: false
  decryption:
    provider: sops
    secretRef:
      name: sops-age
