apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: skyline
  namespace: flux-system
spec:
  interval: 1h0m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: 'flux/apps/skyline'
  prune: true
  timeout: 5m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: skyline
      namespace: skyline
  decryption:
    provider: sops
