- package_facts:

- include_tasks: install.yml
  when: "'consul' not in packages"

- include_tasks: server.yml
  when: "consul_role == 'server'"

- name: Write agent config
  template:
    src: "{{ role_path }}/templates/agent_config.hcl"
    dest: /etc/consul.d/agent.hcl
    owner: consul
    group: consul
    mode: '0640'
  become: yes
  when: "consul_role == 'agent'"
  notify:
    - Restart Consul

- name: Create Consul service definitions
  template:
    src: "{{ item }}"
    dest: "/etc/consul.d/{{ item | basename }}"
    owner: consul
    group: consul
    mode: '0640'
  become: yes
  with_fileglob:
    - ../templates/services/*.hcl
  notify:
    - Restart Consul

- name: Create Consul data directory
  file:
    path: /opt/consul
    state: directory
    owner: consul
    group: consul
    mode: '0755'
  become: yes

- name: Create Consul service
  copy:
    src: "{{ role_path }}/files/consul.service"
    dest: /usr/lib/systemd/system/consul.service
  become: yes

- name: Start & enable Consul
  systemd:
    name: consul
    state: started
    enabled: yes
  become: yes
  register: consul_start

- name: Skip restarting Consul
  set_fact:
    consul_skip_restart: "{{ consul_start.changed | bool }}"
