apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pkg-fogo-sh
resources:
  - namespace.yaml
  - ../_bases/dieppe

configMapGenerator:
  - name: config
    files:
      - config.hcl

patches:
  - path: ingress_patch.yaml
    target:
      kind: Ingress
      name: dieppe
