apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: discord-notifications
  namespace: flux-system
spec:
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
    - kind: HelmRelease
      name: '*'
    - kind: HelmRelease
      name: '*'
      namespace: longhorn-system
    - kind: HelmRelease
      name: '*'
      namespace: kubernetes-dashboard
    - kind: HelmRelease
      name: '*'
      namespace: loki-stack
