apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  type: discord
  username: "The Nitfrastructure™ - Flux"
  channel: "552874056282669072"
  secretRef:
    name: discord-webhook
