apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - persistent_volume_claim.yaml
  - secrets.yaml
  - deployment.yaml
  - image_repository.yaml
  - image_policy.yaml
images:
  - name: ghcr.io/nint8835/hopper
    newTag: main-6233b25-20260620-175906 # {"$imagepolicy": "flux-system:hopper:tag"}
    digest: sha256:5d4b6aa0c4856e28bdbf3be6f924cbafafa6c666df1ce6be16e9784837355a24 # {"$imagepolicy": "flux-system:hopper:digest"}
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: override-namespace
      namespace: hopper
    unsetOnly: true
