apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent

metadata:
  name: victoriametrics-agent

spec:
  selectAllByDefault: true
  remoteWrite:
    - url: "http://vmsingle-victoriametrics.lgtm.svc.cluster.local:8429/api/v1/write"
