apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless-ngx

resources:
  - namespace.yaml
  - persistent_volume_claim.yaml
  - redis.yaml
  - service_redis.yaml
  - secrets.yaml
  - paperless-ngx.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/paperless-ngx/paperless-ngx
    newTag: 2.20.15@sha256:6c86cad803970ea782683a8e80e7403444c5bf3cf70de63b4d3c8e87500db92f
  - name: ghcr.io/valkey-io/valkey
    newTag: 9.0.4-alpine@sha256:d1cc70645bbcef743615463a2fa4616e841407545e18f560aed0c49671a90147
