apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless-ngx

resources:
  - namespace.yaml
  - persistent_volume_claim.yaml
  - redis.yaml
  - service_redis.yaml
  - paperless-ngx.yaml
  - service.yaml
  - ingress.yaml

secretGenerator:
  - name: secrets
    envs:
      - secrets.env

images:
  - name: ghcr.io/paperless-ngx/paperless-ngx
    newTag: 3.2.1@sha256:5fa76604a81df6945086e0837b14b56543d137e8ce4f311cc5d9ebe907e74e79
  - name: ghcr.io/valkey-io/valkey
    newTag: 9.1.2-alpine@sha256:a174b894902bd3367e330d47cc2054367dc4917701776aaf336f41d83b65ec7a
