apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless-ngx

resources:
  - namespace.yaml
  - persistent_volume_claim.yaml
  - redis.yaml
  - service_redis.yaml
  - secrets.yaml
  - paperless-ngx.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/paperless-ngx/paperless-ngx
    newTag: 3.0.0@sha256:80f96a38de1a04c49a466b236b9c34491e6c4b29cc1e216a4a5134ba5dd22059
  - name: ghcr.io/valkey-io/valkey
    newTag: 9.1.1-alpine@sha256:ee91f7a174ac4d6a6b0685b3a60e321f0a9dbbb691f9b0e285be2ba1d1be8328
