apiVersion: apps/v1
kind: Deployment

metadata:
  name: paperless-ngx

spec:
  selector:
    matchLabels:
      app: paperless-ngx

  replicas: 1

  template:
    metadata:
      labels:
        app: paperless-ngx

    spec:
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: export
          persistentVolumeClaim:
            claimName: export
        - name: consume
          persistentVolumeClaim:
            claimName: consume

      securityContext:
        fsGroup: 1000

      containers:
        - name: paperless-ngx
          image: ghcr.io/paperless-ngx/paperless-ngx:2.20.5

          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          volumeMounts:
            - mountPath: /usr/src/paperless/media
              name: media
            - mountPath: /usr/src/paperless/data
              name: data
            - mountPath: /usr/src/paperless/export
              name: export
            - mountPath: /usr/src/paperless/consume
              name: consume

          env:
            - name: PAPERLESS_REDIS
              value: "redis://redis:6379"
            - name: PAPERLESS_URL
              value: https://paperless.bootleg.technology
            - name: PAPERLESS_TIME_ZONE
              value: America/St_Johns
            - name: PAPERLESS_OCR_LANGUAGE
              value: eng
            - name: PAPERLESS_CONSUMER_POLLING
              value: "30"

          envFrom:
            - secretRef:
                name: secrets
              prefix: PAPERLESS_
