apiVersion: v1
kind: Secret
metadata:
    name: secrets
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:2QUQdbmpm13QYCG+h58NT16KxBAvk1lFWojcFL8lIdQ=,iv:cw5PXEVmnijWM+YmyNpRtDacoXcIdVuhXnHYw9Skv1A=,tag:RQudK0dc5aM/MXuNwqyc0Q==,type:str]
sops:
    age:
        - recipient: age1rmn09vuxjzh9wmx4hj8zz72ckgaa3psdzsaglj3all5k7gp5wqpsvvtmz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObzlvWDdtMjdVdnZqWTlj
            T3BaNFEvSFpzMlN3RjdWcThyeFFPVnZjY2hzCnk5c240VTlsNFp2T0ZiSUxPeEVi
            SFEvemE2bnN3NGxEMFUyTXdyMUxscFUKLS0tIHdBR0ZqU1JaKzl2bmVaeWpPTVJH
            NDVDSlc1TEp3QWNReWpIVUtMZzJZZjgKU7Pc/U1pX7g5mzsu6ikYP9evbZVfnPuY
            QKccFM1gZcY/QwvgQ06H0n+E3f81qXp5g1PWaNjBgw7yk2o+QN+10g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-31T23:11:26Z"
    mac: ENC[AES256_GCM,data:kbd3Cl2+iETFm8t5U9SrtB5WCVNQOuSQEy8YcBufOlC8W6BFsy7DAES7fChkWSKoQjaiO7JEtI7b7ohx1QHZ1fp2aPhD/ejWtjFIWZK97RpGUXiKhENCrWi+rWyJjuO9ewrv+GqrEVgtpElLYsVsISHH6tuqv+BgpuLHdbuOU1c=,iv:HuUQeekuoAd9uEWrHo5mRCZIstnKX7MnzzHqM0pMJRs=,tag:JY/47Kq1ZMToXrH9vL2N5w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
