apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: romm

resources:
  - namespace.yaml
  - persistent_volume_claim.yaml
  - redis.yaml
  - service_redis.yaml
  - postgres.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

secretGenerator:
  - name: secrets
    envs:
      - secrets.env

images:
  - name: ghcr.io/rommapp/romm
    newTag: 5.3.1-slim@sha256:974bab5e89cc82d892496256d86ec1d9f24970a2c12854f529275d0c82f37bf7
  - name: ghcr.io/valkey-io/valkey
    newTag: 9.1.2-alpine@sha256:a174b894902bd3367e330d47cc2054367dc4917701776aaf336f41d83b65ec7a
