apiVersion: v1
kind: Secret
metadata:
    name: secrets
stringData:
    ROMM_AUTH_SECRET_KEY: ENC[AES256_GCM,data:xXD9HenYp513T7Pnbj3NalpOJ1s/FJY8rvOv5cfKCYPT9aDUNHFF8SQ2VjSxgG28Yh0zosaMz3YeYrx2UIWjTw==,iv:XGsqLHkTpBPg19WKoeiGM9bi/TLlik5SQMTMO+5zzF8=,tag:1iivKS+h5I3YZG1aWYHLiA==,type:str]
    SCREENSCRAPER_USER: ENC[AES256_GCM,data:+fDORM4yego=,iv:57MJvw2WGOebfvyIAj0IL5PtD6ARKa4A91HE0FEMQoU=,tag:ah4vm632uGk74fNdvzcfIw==,type:str]
    SCREENSCRAPER_PASSWORD: ENC[AES256_GCM,data:0WhiaXFI5jzmYJE=,iv:N0ILX5cxCH+Qnhu33Y1s1InS5UkOImATuAsi79IBDOY=,tag:lBSSiUpRV3hmXf8YVW2OTg==,type:str]
    RETROACHIEVEMENTS_API_KEY: ENC[AES256_GCM,data:8SXzRBjptAa/i1kJmd1kLBucqRab36Y6vDgvYMpNvjI=,iv:wLAG3a8BOpQbE5PF32bY8T55imIjPgORILwF2dpRY4Q=,tag:YuJhtQQow4ByJF1UORg4CA==,type:str]
    STEAMGRIDDB_API_KEY: ENC[AES256_GCM,data:7y6PApIZscL71U1Z+7kGubFF7/P3EwyIOVgxXkRiOfE=,iv:H+P7jPKbn4GXVylTejdz3CvphAO/mfCPdnm4nQvDXHY=,tag:1YJfK/BXx470NQ+ycj5qJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TUxIbXRadkJibzVHSXNo
            djFHOXZLRncrakI2WSt2WDFYeWlTbVpZK3k4CkhFdmpjc3daWmFXam9OTWtrNUFx
            TE1ReXI0VmFwcGNqUWxBekIvdCt1ZHcKLS0tIHBib0Y4ZVloZXdUZk5pN3ZtOHM3
            S3pTM2Z4WlFidFRoUWd5MWh0enFUeUEK7LOo1qg4DFYyUVCATowNuG7a7+/jzun0
            s253/C0oAjkxOIigmxBTpxwjKdhz3VLCIJAK0QP1BQQ/0KBXB/OOtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rmn09vuxjzh9wmx4hj8zz72ckgaa3psdzsaglj3all5k7gp5wqpsvvtmz7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T00:16:21Z"
    mac: ENC[AES256_GCM,data:HDVz5y9D7nhdom3asGo0y2PkEcCSN3HdvdWi1UJ18aC1bMmCEJxMk6NjIGIYk0ZGR93avdy/QFXlXsc1OCV8h8Nd4VPyN71DOkW/s0rAnu8INlMjHgM9wRGUN0PNRX5OrBWK2T66rg2VxjXFpDPLrNCKCYEBpNSx5e81sOuFqBM=,iv:/YIQv+Fgu6QNmBeusxMBiKVddrXArkLb/jaxV34ozVA=,tag:uK9orHhuEFtH4F+x92IWvg==,type:str]
    version: 3.13.2
