apiVersion: v1
kind: Secret
metadata:
    name: secrets
stringData:
    ROMM_AUTH_SECRET_KEY: ENC[AES256_GCM,data:Up0/Fakg1ymHAPFP8POVmnLbxcqlxFaG8AAzKV/1tCd3O4wdLp+khgyABhfAj/Wg7BzcM5/kFwR3TYqt1EGoUg==,iv:cfTjeyUxyCXAOt4AQyoCSeJ+JNhM2VumWQs0fpUqfSY=,tag:yNtaEJ/IyMx/kiB66X8Q6Q==,type:str]
    SCREENSCRAPER_USER: ENC[AES256_GCM,data:lk5MLbNjaQA=,iv:xaWfyknAQvpdxZ18LNdhcKizJHsZn/E9a4gWxJUXCgo=,tag:2y+GWo9iIG59BsO9Zyayqg==,type:str]
    SCREENSCRAPER_PASSWORD: ENC[AES256_GCM,data:FKDTjBUnR0DA9dY=,iv:26xIp5RA2MAptiiktKkSyMCHxpDp3rjVELT6+NqKqLM=,tag:3TuIFjOBRPenOnQWwpBecQ==,type:str]
    RETROACHIEVEMENTS_API_KEY: ENC[AES256_GCM,data:NlvfGYnfSSyNKf9PNzJbGDMMBHZxEw+pwRsgma4e/+g=,iv:xwOJo4UXA+AAHG2HZLJRIKtyqwXd+V/srShZjdP0eQg=,tag:/2UXr8dyVfjUDxQGaBbreg==,type:str]
    STEAMGRIDDB_API_KEY: ENC[AES256_GCM,data:kNSJb99bT6+HB8KVpViPAcO0eeRBwmhWgxPL7YDSCBI=,iv:bU6rPiP1WJUsOeIRO3fW++8pSojUFZ65wvJRnEfMPSs=,tag:FxdBk0Eo1o9xm39vGvNHXg==,type:str]
    IGDB_CLIENT_ID: ENC[AES256_GCM,data:He6GJPp8/iBIQ/0w9oQbdeFKUusrGR7+M9M+slKr,iv:TiG8ByjR4ixh09MVJgouokiLZJ+rKPriyFFnLb2hq7M=,tag:KDN/xWZZAsxskSfEoD3YFw==,type:str]
    IGDB_CLIENT_SECRET: ENC[AES256_GCM,data:AD1/wJX8LduDYQSIwtuqlEFcSXJRq39QRrxXlfHv,iv:WuEhqEm1DEe4csFBwG9QPABIy68Zelb1eNfXxzzg+2I=,tag:XJgWq2vrtjZAFgkx/V0p4Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMnNFNmFNUjJqU0EvTTJv
            QTlhdWx0RFBCMHBVNUx0QmdDTlBSK1JzT0FzCnZRd2pYQXhqc3VtejFINmJHb0Mv
            c2hNN3laOVVMNUxvTDNwOTRQaTdCWE0KLS0tIDh6dENKWnFUL3ROVzJUbHZGcklW
            T2hidW9ZRHNRaFllU3k4clZFNkJyQ28KnFIENHom0cWut45kxeDRddYj3J63h19t
            Eer3x/wY0N4EraMSDmkYppXFTf9caEdly9YThwOwSWDRw3YNRW/gTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rmn09vuxjzh9wmx4hj8zz72ckgaa3psdzsaglj3all5k7gp5wqpsvvtmz7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T00:55:16Z"
    mac: ENC[AES256_GCM,data:xHJeoX3Z9jKFlpan9DWzKFRJAHECK+KtykWafl5oD6Fo9u2tZxTCSn7zA7jiNriJO/sdb0f5JTS3vQjK5whe5stnTeIo+/2pz5KqYYfFhZhEi1o+FO8R4b/gASVIWpesziGPglDlEsehILj3Ymk831A8PNp3oNTMtyhQk5ceVaQ=,iv:dMnjryhzvXp/yXLX9Rrk8/RtDjkgs8VNN5YoeyzPUtY=,tag:mMhxvPPx1Cbu9TIz1/fFog==,type:str]
    version: 3.13.2
