apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare-ddns

resources:
  - namespace.yaml
  - secrets.yaml
  - deployment.yaml

images:
  - name: favonia/cloudflare-ddns
    newTag: 1.16.2@sha256:bc53b40b13c8b2a84e9b93c21f65fcd7d574b741014fb93912eb9efd93015aa2
