apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflare-ddns

resources:
  - namespace.yaml
  - secrets.yaml
  - deployment.yaml

images:
  - name: favonia/cloudflare-ddns
    newTag: 1.17.0@sha256:61013368c8f95981c0bb8bf56d962078d8b4e95724a554fa2dabb20d6e478097
