kind: Secret
metadata:
    name: secrets
stringData:
    cloudflare-api-token: ENC[AES256_GCM,data:xYX0Yvo7qnQ94WgfenreUi6t6pjeiLgtAU9wbiHz2/NRUvshHhw+gg==,iv:0lwcu5WUdP/KUJHosjbPlW/nIt0UxdFSNKFP6P7fKeQ=,tag:V6hmyxXC7Cd6lUDl2rGvhA==,type:str]
sops:
    age:
        - recipient: age1rmn09vuxjzh9wmx4hj8zz72ckgaa3psdzsaglj3all5k7gp5wqpsvvtmz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5a0UzMTNZTGpnRkU2eVU3
            Mll5dm9BYlpZazBrY1FJMnpETk1WbWJrRUQwCm0wMmZqaDVKK3hPRnMxY2h6YnVW
            aC9tRFI1KzhCRVJMZHNvREdxQ0h4aEUKLS0tIFRIc3J3VUZORCs0Q0VYTGlPd0dF
            S2pnS2poUUVadlFEOGtsVFN4ZUZyR1UKj5sPObrTCvY3pJpVOug6xBfnUn4Psr7v
            v+b6tNMLRXyw7NcKK+yP/ndmGZGdwy7DAg6pTicX2t4VEIQxjBkU/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-16T23:33:33Z"
    mac: ENC[AES256_GCM,data:GSMcovpXTBc2fAoHyHeMAuItE056lNT99laj7vBTRl4xAeGROhhQQgtJA7dtIF+DdvUV4+c6mxADT02N0waQL4u5bRpJFdlLAAr9CYHNovDxG26JwzIdQQ6pQMpKxiIiNl+xO5yvi6iM0jiEWiDT+mvWZ9ywjPPfso515iFs6jg=,iv:UglDt6LDpWG5xVSxl7zkoLVntGGvpMWEH7A56rsmOAo=,tag:VkY9tWgk98NdmT0eq6fH6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
