apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.yaml
  - deployment.yaml
  - image_repository.yaml
  - image_policy.yaml
images:
  - name: ghcr.io/fogo-sh/borik
    newTag: main-c37370c-20260318-173516 # {"$imagepolicy": "flux-system:borik:tag"}
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: override-namespace
      namespace: borik
    unsetOnly: true
