apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: borik
resources:
  - namespace.yaml
  - deployment.yaml
secretGenerator:
  - name: secrets
    envs:
      - secrets.env
images:
  - name: ghcr.io/fogo-sh/borik
    newTag: main-8e4b9df-20260913-131441 # {"$imagepolicy": "flux-system:borik:tag"}
    digest: sha256:0b18d0672b6f3d8d8e75c47a78753aa53b9f6fbe71892ab4009320fa0b9124fa # {"$imagepolicy": "flux-system:borik:digest"}
