apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.yaml
  - deployment.yaml
  - image_repository.yaml
  - image_policy.yaml
images:
  - name: ghcr.io/fogo-sh/borik
    newTag: main-9543753-20260516-151047 # {"$imagepolicy": "flux-system:borik:tag"}
    digest: sha256:c128d35391384fd16284cad514ce9e66787f6f38f1417bbb94798f427fc9f0d4 # {"$imagepolicy": "flux-system:borik:digest"}
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: override-namespace
      namespace: borik
    unsetOnly: true
