apiVersion: v1
kind: Secret
metadata:
    name: secrets
stringData:
    TOKEN: ENC[AES256_GCM,data:HfI3+8GnZsBV+P0CI0G85Sylns5R4Vu+yPmCWLu8hA43kwW/Mx7R0vJD6+VlCnRRQR6oddqFQCKhoXg=,iv:IBgXRyrjEI2nCDt3EGR4vL0vnlnsZ/bkpZ/1hdq7hq8=,tag:8o1pRq9zXjj4nWJw1jqdJw==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:5AlDBst/pCS/fnsiMBXbKRWPlfp7ll2SrA==,iv:nue216kTajr2gcbPsiGdmr23/z4Z+2QzrwGpBjJmeyA=,tag:y+wjIJHsY7nziOyJtUEe5A==,type:str]
    APP_ID: ENC[AES256_GCM,data:NCsnaVYS7B+MJQ8KPQAcHhMm,iv:qjhRq4TlS7+jGu7P0VnOwo+RX5QNLP0vuO92h2tjQTg=,tag:NI5e57SKPpetoYm/4K+E0w==,type:str]
    REGISTER_SLASH_COMMANDS_GLOBALLY: ENC[AES256_GCM,data:wTSSJg==,iv:ZA59+RX9ws7zyU+bZK6tJzk79NCCr5DvlYao4DWntIA=,tag:OAkiJ0zG9l6sjEuEfHIBBA==,type:str]
sops:
    age:
        - recipient: age1rmn09vuxjzh9wmx4hj8zz72ckgaa3psdzsaglj3all5k7gp5wqpsvvtmz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0QVZ0NlRYWVVqWUpjZkpP
            YXZIbGsvditiKzZ6SkVvaWVDdU1yaHNsaEQ0Cjc0R1l6SDBVZDNGVnllbUFhRU1z
            MWFaODhPQ0pxVEFIMlhpSWczTHFsem8KLS0tIGxwN0ZlVWd4UmVDOXNHUVYwMDNN
            eGZMV1NLNXZSdUI5d3FINVFIdFAyeGMKeYz3IDomxTmZLSjHWfWcyCHYlgi0KT8r
            X4j4sDMy0JKrRMZDJ4v0pXC7/w/8ScW8we1bCbLKr+DO/fB7c4vynw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T17:44:09Z"
    mac: ENC[AES256_GCM,data:E72uTb1V54LQZ3mArjQ+9DZdQ9343LnxmKwNI/44qQr8x7RnFFRqP9Xvw1w9tFwN+8qLPmxclHo5FGHyEORGDSVT4MUzvujmde88C6R+vW7F7bNK0ruH9eMvA5XRDc2w2d9E+pA28FsIB4bdxc+eLG8UypXohUy99m+/FXlC9Ts=,iv:z2zR27wi6BgZ4I0FzUQlic76pcRefoqJkx7Gz6X5JCA=,tag:cP0lg5c2NrzntREhJCgJRg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
