apiVersion: v1
kind: Secret
metadata:
    name: secrets
stringData:
    TOKEN: ENC[AES256_GCM,data:u+DHIL/tDTsk5izM1hAHsBH4jea07I2rIJdJXMVLcuhTKy5DGuPLvFCvwTednMaqZokbdBaxUhin8hs=,iv:JjAFqaA1tlEzfuWF8fxJzENsdjtDeRiBVTFQATSHoOg=,tag:rTT5vKCMTGF+wVqQZJ6b+g==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:6AnbkDJ1IRlMPkA73zhYKf1fkD4YBQRvpQ==,iv:FQZbf/VgE2cgsnirLcIWsmG6tcEo7qyqAw8xsW+fAnA=,tag:143s+NgDQ43h4wxbngAiCg==,type:str]
    APP_ID: ENC[AES256_GCM,data:cZOK/xCdBmAxw6nvuBLxL1Gh,iv:05hfr6+pceidPXTa7eud9XEM4a1jwZ0cT9G5xYkBvLw=,tag:L85zSwtwvtAB0FBnWUvG6g==,type:str]
    REGISTER_SLASH_COMMANDS_GLOBALLY: ENC[AES256_GCM,data:kLzK8Q==,iv:RFyRqbbBxd60joIsWnJhnOmEmIJ9375/oMea6EnlJMU=,tag:kXNTu/5vfMY7E8vXb+xAIQ==,type:str]
    PREFIXES: ENC[AES256_GCM,data:hOTjDozHlFQ=,iv:19C1xG4pl6wIFY8kyB1gmYH2BaGoDFcXginMyGef14s=,tag:0++KVOUOprFM4VDrgRWbAg==,type:str]
sops:
    age:
        - recipient: age1rmn09vuxjzh9wmx4hj8zz72ckgaa3psdzsaglj3all5k7gp5wqpsvvtmz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqT1NrVUlIM0JrT0ZqN0ds
            SmtnOHNFT2VWNWx1R3hmMXIxdTVWdEc3d25FCmxza09hcXBEZ0FDWlRTaTBqcllL
            N2tqRDRORS9pajVhOHFMc2tDeGxUOG8KLS0tIDZ5VVZjUWJzQ0pLODIzZy9yMjVm
            ZG9majdzWUVpdHlhTmhrRmhob0RkTUkKuUrS+azr3WItcGKZcZdPG2RNjBHwwr9l
            nd8cgIbcLCDtf41u5tDOQTcFamdmky9/JXt+erkxZv7uopzMEowCcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T18:13:03Z"
    mac: ENC[AES256_GCM,data:cZpn+g/gl6nGxinsLbBT6Y9ICnj5LsAILXvssg/QZZTIE9G5fsF7WUg+zM81AGzFkX+UslOIHS9NdM3OgEUHAf1iaTC00F6HRpSn6+9kMz3rTANMxzSzdnHDv1Lc6alsg1773C7vRURSBJx3z8x5nb70xD3BhkbuSowgeIqKpLQ=,iv:kHESy0/KyDv+v63gwqwiWwZWB9vfFaSmdMzsIT1UW20=,tag:UYmkIb3svzJwSNSoxSvPuA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
