- name: Install nfs-common
  apt:
    name: nfs-common

- name: Create NAS mount directory
  file:
    path: /mnt/shared
    state: directory

- name: Mount NAS
  mount:
    path: /mnt/shared
    src: "{{ nas_ip_address }}:{{ nas_src_path }}"
    fstype: nfs
    state: mounted
