apiVersion: batch/v1
kind: CronJob

metadata:
  name: gramfel

spec:
  timeZone: America/St_Johns
  schedule: "30 14 * * *"
  successfulJobsHistoryLimit: 0
  
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: gramfel
              image: ghcr.io/nint8835/gramfel

              envFrom:
                - secretRef:
                    name: secrets
                  prefix: GRAMFEL_

              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
        
          restartPolicy: Never
          
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
