apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gramfel
resources:
  - namespace.yaml
  - job.yaml
secretGenerator:
  - name: secrets
    envs:
      - secrets.env
images:
  - name: ghcr.io/nint8835/gramfel
    newTag: main-d161ad7-20260917-144404 # {"$imagepolicy": "flux-system:gramfel:tag"}
    digest: sha256:dc16add30d058c590ec48872cfea5cddf94f4db367be414ab404280caaf2e809 # {"$imagepolicy": "flux-system:gramfel:digest"}
