apiVersion: v1
kind: Secret
metadata:
    name: secrets
stringData:
    WEBHOOK_URL_GENERAL: ENC[AES256_GCM,data:5NNUQjiCjBxbetar6rees3wkiYH3AwCnforHfYb5EpEzwa/mCLI1qzkSW/kSxtgshnnK+48yDNzGkV+NqHZ5Ixt/Lim3OAGAtJ3Uw69q1PG8UOvhz8xAvfYZnIUPGIoVdAOC7abug/EstOlIdGk3Zm2xSIvVc6HRQB7wgtpUTA==,iv:tzDMLyvis+GBIhonvQCKO68o2vKBhKay/WJ9gYbmvok=,tag:MLNTNqa5eJerTFyxyx816A==,type:str]
sops:
    age:
        - recipient: age1rmn09vuxjzh9wmx4hj8zz72ckgaa3psdzsaglj3all5k7gp5wqpsvvtmz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTmE3T1YycDJrZU5kb1Vp
            NHJ1ZXJGblVYNTQ1dmhuUVNoS0s5K2lhejJVCkJPVFUzVEJ4aFBZKzVJYTQyY0gv
            VlVsVXV0YitoZGVoWHB0YXB4ai9PdjAKLS0tIEhBRG8vaW91NGVGWGNSSTE3Smha
            eStyOVRib2xjb0FIdCsveUdJYnhRQ3cKDLPnH5XaiPJRxT57mSy62M0/Ux8ofMaz
            w/kZSxbLL7PHY64YbVrq+A84uTXFKnqjYScCZH7i9XjLEvDWDBlzSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T23:59:17Z"
    mac: ENC[AES256_GCM,data:kEgIQHcVNoacpYkijeQHZnHrXcNP05BZEG/TDK15Mz9VTY67j78VSyif7nDGjDNwuqkKfjgYscdWe2moJmTuOsulfNtjH6EK9trUESQOjEu+VRebJFEWFTSbSkbODbRpKnBdvCydlVlikogfQPNylCyDDsn24zJ1+5d5VHctjcE=,iv:8zsT96HmxwxzJEwYm64Xjj/4hJSa66f9bCfnHIepp3I=,tag:MVyzEFARqwW5EjsoTxkYLA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
