apiVersion: v1
kind: Secret
metadata:
    name: stocky-discord-token
    namespace: stocky
type: Opaque
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:onNac8rm1jpv/RTbDFUxrWJX1K/BpPAdLcyO+zxh7Ok/0cpJzvmrMoPaozeZUIyTQPGNQp6CsX5P5xmznUZtVmXeVLcYkvf0,iv:Qkphhq+z+0EdUGUR+7U9cmV/GxnkZ8KlvkcOK0Q0b/M=,tag:vgNASXF6/QnPTXOfZVbm2Q==,type:str]
sops:
    age:
        - recipient: age1rmn09vuxjzh9wmx4hj8zz72ckgaa3psdzsaglj3all5k7gp5wqpsvvtmz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4V3hMcDhHcXo2d0NpZzhq
            cWxaRjdIbElya3Rxc0EwMTFyck5MSU8wclcwCkhvNkJuNEk5aDlSM1VoR2NpWlg1
            bVdQZW16cTJBYnlhWWVBTWwvQXByaE0KLS0tIDQ0N1RZSEpnR25xWTluYXJQVVdu
            YnRWK0ZZZnVtOG9CMS9vN2pObnZBY3cKeho02pIHKml7Zh5vD5k7+mzIac6X0cWv
            xGR+nVO6HKymrr5HUtvQycS6Z2K0cMz1BnqHaXjtjeYPC+AoEE5vVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-12T12:49:57Z"
    mac: ENC[AES256_GCM,data:9sBEZPwjl8/A5x1uXT2h5f1lU8sgYGM3rIduA9GDcw3TqwqiWev4sC96j9Wa+ZlnK7ARdzRcnd+fdQ+H+vH5v8xr1N2n6Y94FNrZ/3kjpvQWJ7vU8NhaaKt3I3qkWeC2BoPRQWIC0uYpcefkXADTmkSUTdi4Onsxk8CedgVj5hk=,iv:9owY68rdOhdv6A/b8V/dZTcjsABtlEymkCNjkBHdrSk=,tag:ykMuzqsPZkzjmFaTf2Smug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
