apiVersion: source.extensions.fluxcd.io/v1beta1
kind: ArtifactGenerator

metadata:
  name: flux-services
  namespace: flux-system

spec:
  sources:
    - alias: repo
      kind: GitRepository
      name: flux-system
  # Leave revision unset so only changes to each artifact's contents change it.
  artifacts:
    - name: cloudnativepg
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/system/cloudnativepg/**'
          to: '@artifact/'
    - name: metrics-server
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/system/metrics-server/**'
          to: '@artifact/'
    - name: keda
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/system/keda/**'
          to: '@artifact/'
