apiVersion: source.extensions.fluxcd.io/v1beta1
kind: ArtifactGenerator

metadata:
  name: flux-services
  namespace: flux-system

spec:
  sources:
    - alias: repo
      kind: GitRepository
      name: flux-system
  # Leave revision unset so only changes to each artifact's contents change it.
  artifacts:
    - name: cloudnativepg
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/system/cloudnativepg/**'
          to: '@artifact/'
    - name: metrics-server
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/system/metrics-server/**'
          to: '@artifact/'
    - name: keda
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/system/keda/**'
          to: '@artifact/'
    - name: monitoring
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/system/monitoring/**'
          to: '@artifact/'
    - name: nfs-csi
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/system/nfs-csi/**'
          to: '@artifact/'
    - name: cert-manager
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/system/cert-manager/**'
          to: '@artifact/'
    - name: cert-manager-configs
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/system/cert-manager-configs/**'
          to: '@artifact/'
    - name: webhook
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/system/webhook/**'
          to: '@artifact/'
    - name: traefik
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/system/traefik/**'
          to: '@artifact/'
    - name: traefik-configs
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/system/traefik-configs/**'
          to: '@artifact/'
    - name: metallb
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/system/metallb/**'
          to: '@artifact/'
    - name: metallb-configs
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/system/metallb-configs/**'
          to: '@artifact/'
    - name: borik
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/apps/borik/**'
          to: '@artifact/'
    - name: gramfel
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/apps/gramfel/**'
          to: '@artifact/'
    - name: cloudflare-ddns
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/apps/cloudflare-ddns/**'
          to: '@artifact/'
    - name: homeassistant-proxy
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/apps/homeassistant-proxy/**'
          to: '@artifact/'
    - name: plex-proxy
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/apps/plex-proxy/**'
          to: '@artifact/'
    - name: pkg-fogo-sh
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/apps/pkg-fogo-sh/**'
          to: '@artifact/pkg-fogo-sh/'
        - from: '@repo/flux/apps/_bases/dieppe/**'
          to: '@artifact/_bases/dieppe/'
    - name: pkg-nit-so
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/apps/pkg-nit-so/**'
          to: '@artifact/pkg-nit-so/'
        - from: '@repo/flux/apps/_bases/dieppe/**'
          to: '@artifact/_bases/dieppe/'
    - name: litellm
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/apps/litellm/**'
          to: '@artifact/'
    - name: scribe
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/apps/scribe/**'
          to: '@artifact/'
    - name: interruption-spotter
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/apps/interruption-spotter/**'
          to: '@artifact/'
    - name: planespotter
      originRevision: '@repo'
      copy:
        - from: '@repo/flux/apps/planespotter/**'
          to: '@artifact/'
