apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: cert-manager-configs
  namespace: flux-system

spec:
  interval: 1h0m0s
  dependsOn:
    - name: cert-manager
    - name: traefik-configs
  sourceRef:
    kind: ExternalArtifact
    name: cert-manager-configs
  path: './'
  prune: true
  timeout: 5m
  wait: true
