apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - artifact_generator.yaml
  - ./notifications
  - ./webhook
  - ./image-updates
  - ./images
  - metrics-server.yaml
  - keda.yaml
  - cloudnativepg.yaml
  - monitoring.yaml
  - nfs-csi.yaml
