apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: traefik-configs
  namespace: flux-system

spec:
  interval: 1h0m0s
  dependsOn:
    - name: traefik
  sourceRef:
    kind: ExternalArtifact
    name: traefik-configs
  path: './'
  prune: true
  timeout: 5m
  decryption:
    provider: sops
