- op: add
  path: /spec/tls/0/hosts
  value:
    - marketplace.ctsnl.ca
- op: add
  path: /spec/tls/0/secretName
  value: marketplace-ctsnl-ca
- op: add
  path: /spec/rules/0/host
  value: marketplace.ctsnl.ca
