apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shopkeeper-cts
resources:
  - namespace.yaml
  - ../_bases/shopkeeper
configMapGenerator:
  - name: config
    envs:
      - config.env
secretGenerator:
  - name: secrets
    envs:
      - secrets.env
patches:
  - path: ingress_patch.yaml
    target:
      kind: Ingress
      name: shopkeeper
