apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: instatus-cluster-monitor-agent
  labels:
    app: instatus-cluster-monitor-agent

spec:
  selector:
    matchLabels:
      app: instatus-cluster-monitor-agent

  template:
    metadata:
      labels:
        app: instatus-cluster-monitor-agent

    spec:
      containers:
        - name: agent
          image: ghcr.io/nint8835/instatus-cluster-monitor-agent:latest
          imagePullPolicy: Always

          env:
            - name: INSTATUS_MONITOR_HOST_IDENTIFIER
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

            - name: INSTATUS_MONITOR_SHARED_SECRET
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: secret

            - name: INSTATUS_MONITOR_SERVER_ADDRESS
              value: "https://bootleg-technology-instatus-cluster-monitor.fly.dev/ping"
