apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: instatus-cluster-monitor

resources:
  - namespace.yaml

secretGenerator:
  - name: shared-secret
    files:
      - secret=secret.encrypted
