apiVersion: v1
kind: Secret
metadata:
    name: secrets
stringData:
    DISCORD_TOKEN: ENC[AES256_GCM,data:Rj89w93Cf0JNyxUASTQ7ZW0tPGN1q9zfsYCWS1qf9n3pi8jhsXQf1ZfE92+GYJEiy7OeWX2hiaePXqrihpyxAG2EKNvLhg==,iv:iyfSu3uVXEC/ibToy/jyk8CYws/WtpqrdBH6Nhi2tEw=,tag:cL8EZrneCV/cOrx31bd43A==,type:str]
    DISCORD_APP_ID: ENC[AES256_GCM,data:yxixJd8M8w2GciUDAvWaA5QK,iv:b4yNl/ONW0yGzIpOVyz9rPcafIJgASOvP6U9RH5UCv4=,tag:HYrgVFDr0cIoSs5k8la+1w==,type:str]
    ADVENT_OF_CODE_SESSION: ENC[AES256_GCM,data:0l+ziHxSIB9E0sgClMJ9EFtQ175FtdYoACbPVRbhUS8tuDZeGcKaIzaxqWufterHWvkZyaOGttgmcvBzfroy/hMl7vwszm40PzkLzDpqtPy9t6Wz/X7DgYIIgfSNw+IS/1oimqdCY01dCNO7Yw5GrfAnmQrQO3qiNzj9LFn57mc=,iv:4Pp1Btk4zuYopVFZ4DsiUWjT58Bq73+kWedYxfJVjOo=,tag:fti2i3DegKH3hd0XtZ0+AA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rmn09vuxjzh9wmx4hj8zz72ckgaa3psdzsaglj3all5k7gp5wqpsvvtmz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUitFTG5wekNFdm1KbWVE
            U0p0T3gwc3Fhc2I0MWRKUG52RHMybG95VjM0CjVFMnhBU3ZtcFhqTTkzRDE3cVd4
            WHdSOXRwZXpTRmtBaE5rc1k0RE1aMzgKLS0tIEg3emladnRrSTJDT1VJc3c2YS8z
            bk9wK0xWd3RRU0sxL3MzMjhLWThPMU0KUuzmNu9jcO8VfNh9z+CknxQI9WxR0QSl
            +hMQGBq3IFRBEAOLa9NYkylPsbeDzACfHuRt5tF6zwSRUi6J4ziNjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-30T19:45:20Z"
    mac: ENC[AES256_GCM,data:B4DmA5BUyWwNlqHuTGAUdMxsofzVV7ZBeME6s+8+LDhPvFPWZqk5JQb3RJqNr/t8QI7OEY4Sp9CJaAy8Z5AGug9Xt+pZSzE18PzaDZDmR71uFvvdPyoX4ax6zgQ/TEXEAQKLCRbGMfrHLBG2ikRuDj063vpyCLAN4egLv/cWOXE=,iv:M5q09UET6/2Sgf/G3j//FF/Dl9y/uMwFRKbzXTtGkgM=,tag:lSNu/AFYVV2DK7ws9lv0nQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
