apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.yaml
  - persistent_volume_claim.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - image_repository.yaml
  - image_policy.yaml
images:
  - name: ghcr.io/fogo-sh/grackdb
    newTag: main-c37370c-20260318-173516 # {"$imagepolicy": "flux-system:grackdb:tag"}
    digest: sha256:829628850aae54db70c3c2588966f6321cf46fa7dcf292d5d35055391de60523 # {"$imagepolicy": "flux-system:grackdb:digest"}
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: override-namespace
      namespace: grackdb
    unsetOnly: true
