apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grackdb

resources:
  - namespace.yaml
  - secrets.yaml
  - persistent_volume_claim.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
