apiVersion: v1
data:
    JWT_SIGNING_SECRET: ENC[AES256_GCM,data:WpK8ci06wUgBicQlCXNfnoy+zh1TD1jBaUyxqQ==,iv:ZuzyENJcsFXAOKgVDk4MUQlPwL8B9kF0ZBhvFFFufOw=,tag:HBzNg6UFsOJJSWTkzHOnsQ==,type:str]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:IGYqZH8OKf8KjEzsliCO6QzQfALyAEhW+Qrs8Q==,iv:1BaywE29H9xI1RVT6aJpxyW6WsI2pjXRohBNn+Q2vGk=,tag:oRpv0Wh7yZ1XnYLbsYAilQ==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:Ljz/d5aloCSeVv8ws3YakOLYavDfCbYcXgnYc/14uGk7XApKxxLcNyjsuqtm+04f/VCB7py2G7E=,iv:efiZlk5yOirPkkdYN0ymDTfah8eknGqe4WZZKxo0TiQ=,tag:CMvmqPMUrYKgxfxJBtDIqw==,type:str]
    DISCORD_CLIENT_ID: ENC[AES256_GCM,data:WwWlX3cCJMw+jAarg25aqsCMPKgFwpC+,iv:tavCOGttCEP2c/OX/VgmW0j9I1nTxHpZtqhU1IB+9vw=,tag:hiVR/Q1HwcTgH+7d0gw9Ww==,type:str]
    DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:r5L9hdexx12UwKiIzzOav8ELdFEdi5yQHJ9IHoRN7aBYOZwTSNWV2WohqnI=,iv:BQuEzJOiyGidD1riwjaojAeOtb9Ri4AjiRkNrstD5kQ=,tag:dv+yT/PR13uhLUX8DRAQ4Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rmn09vuxjzh9wmx4hj8zz72ckgaa3psdzsaglj3all5k7gp5wqpsvvtmz7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNjJxVGo3ZHlsT20zd01K
            WW45cHpaZXkyTlJyTjZOcFduTVEwckYyWUhZCnYvOVFVb25MYXc5QUFaZ05SL09E
            bGJQZjVVckFFSUhFOVZIVTJncGdGeWcKLS0tIDR4Wm5uNkh0VjZ6cHhnZ1QvbldO
            dlRUb1FRNDl5eUI0T0poWFVaelNEU0EKpnMs/UvSxm02L8mJHyLK1xQt6T8WJ/vM
            XEbaskWuG9jLo01qrCdCxRE8M3ghY+oS2GiLJ0artWnUmXEhh0ehLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T23:33:40Z"
    mac: ENC[AES256_GCM,data:gBlhE7OJNhKAn6QXTHki3tlWIzcYNeSlWIeYR0NfPNO4sfIZ81OBjm9hQG0FB95eH1poZNJckR1XQrt9W8zv95h/fIP6bFuGNyKjrSPLoqzaT8cv6JGuyk63V4OuRNVEwFez4ja0M9DofX0cRVBh+DStrztUM8WKexwvN70CNE4=,iv:oHwHWKrD9ZWbSwWbDn5ekcCxA9eBNEx2W5avSo6g24k=,tag:WGZYi7HKZtxr5JTQdOo0ow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
