services:
  traefik:
    image: "traefik:v3.6.14"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - ingress
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=ares_ingress"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.forwardedHeaders.insecure=true"
    ports:
      # TODO: Set up HTTPS
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro,Z
  
  open-webui:
    image: "ghcr.io/open-webui/open-webui:v0.9.2"
    restart: unless-stopped
    networks:
      - ingress
      - inference
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.open-webui.rule=Host(`ares.internal.bootleg.technology`)"
      - "traefik.http.routers.open-webui.entrypoints=web"
      - "traefik.docker.network=ares_ingress"
    volumes:
      - open-webui-data:/app/backend/data
  
  llama:
    build: ./inference-service
    restart: unless-stopped
    volumes:
      - /data/models:/models:ro,Z
      - ./llama-swap-config.yaml:/app/config.yaml:ro,Z
    networks:
      - ingress
      - inference
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.llama.rule=Host(`llama.internal.bootleg.technology`)"
      - "traefik.http.routers.llama.entrypoints=web"
      - "traefik.http.services.llama.loadbalancer.server.port=8080"
      - "traefik.docker.network=ares_ingress"
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - video
    security_opt:
      - "seccomp=unconfined"
  
  litellm-db:
    image: postgres:18.3
    restart: unless-stopped
    volumes:
      - litellm-db-data:/var/lib/postgresql
    networks:
      - inference
    env_file:
      - ./litellm-db.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d litellm -U llmproxy"]
      interval: 1s
      timeout: 5s
      retries: 10
  
  litellm:
    image: ghcr.io/berriai/litellm:v1.81.9-stable
    restart: unless-stopped
    depends_on:
      litellm-db:
        condition: service_healthy
    volumes:
      - ./litellm-config.yaml:/app/config.yaml:ro,Z
    command:
      - "--config=/app/config.yaml"
    networks:
      - ingress
      - inference
    env_file:
      - ./litellm.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.litellm.rule=Host(`llm.internal.bootleg.technology`) || Host(`llm.ops.bootleg.technology`)"
      - "traefik.http.routers.litellm.entrypoints=web"
      - "traefik.http.services.litellm.loadbalancer.server.port=4000"
      - "traefik.docker.network=ares_ingress"
  
  ultrafeeder:
    image: ghcr.io/sdr-enthusiasts/docker-adsb-ultrafeeder:latest-build-916
    container_name: ultrafeeder
    hostname: ultrafeeder
    restart: unless-stopped
    networks:
      - adsb
    device_cgroup_rules:
      - "c 189:* rwm"
    ports:
      - 1090:80
    environment:
      - LOGLEVEL=error
      - TZ=${FEEDER_TZ}
      - READSB_DEVICE_TYPE=rtlsdr
      - READSB_RTLSDR_DEVICE=${ADSB_SDR_SERIAL}
      - READSB_RTLSDR_PPM=${ADSB_SDR_PPM}
      - READSB_LAT=${FEEDER_LAT}
      - READSB_LON=${FEEDER_LONG}
      - READSB_ALT=${FEEDER_ALT_M}m
      - READSB_RX_LOCATION_ACCURACY=2
      - READSB_STATS_RANGE=true
      - ULTRAFEEDER_CONFIG=
        adsb,feed.adsb.fi,30004,beast_reduce_plus_out;
        mlat,feed.adsb.fi,31090;
        adsb,in.adsb.lol,30004,beast_reduce_plus_out;
        mlat,in.adsb.lol,31090;
        adsb,feed.airplanes.live,30004,beast_reduce_plus_out;
        mlat,feed.airplanes.live,31090;
        adsb,feed.planespotters.net,30004,beast_reduce_plus_out;
        mlat,mlat.planespotters.net,31090;
        adsb,feed.theairtraffic.com,30004,beast_reduce_plus_out;
        mlat,feed.theairtraffic.com,31090;
        adsb,data.avdelphi.com,24999,beast_reduce_plus_out;
        adsb,skyfeed.hpradar.com,30004,beast_reduce_plus_out;
        mlat,skyfeed.hpradar.com,31090;
        adsb,dati.flyitalyadsb.com,4905,beast_reduce_plus_out;
        mlat,dati.flyitalyadsb.com,30100;
        adsb,feed1.adsbexchange.com,30004,beast_reduce_plus_out;
        mlat,feed.adsbexchange.com,31090;
      - UUID=${ULTRAFEEDER_UUID}
      - MLAT_USER=${FEEDER_NAME}
      - READSB_FORWARD_MLAT_SBS=true
      - UPDATE_TAR1090=true
      - TAR1090_MESSAGERATEINTITLE=true
      - TAR1090_PAGETITLE=${FEEDER_NAME}
      - TAR1090_PLANECOUNTINTITLE=true
      - TAR1090_ENABLE_AC_DB=true
      - TAR1090_FLIGHTAWARELINKS=true
      - HEYWHATSTHAT_PANORAMA_ID=${FEEDER_HEYWHATSTHAT_ID}
      - HEYWHATSTHAT_ALTS=${FEEDER_HEYWHATSTHAT_ALTS}
      - TAR1090_SITESHOW=true
      - TAR1090_RANGE_OUTLINE_COLORED_BY_ALTITUDE=true
      - TAR1090_RANGE_OUTLINE_WIDTH=2.0
      - TAR1090_RANGERINGSDISTANCES=50,100,150,200
      - TAR1090_RANGERINGSCOLORS='#1A237E','#0D47A1','#42A5F5','#64B5F6'
      - TAR1090_USEROUTEAPI=true
      - GRAPHS1090_DARKMODE=true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - ultrafeeder-globe-history:/var/globe_history
      - ultrafeeder-graphs1090:/var/lib/collectd
      - /proc/diskstats:/proc/diskstats:ro
    tmpfs:
      - /run:exec,size=256M
  fr24:
    image: ghcr.io/sdr-enthusiasts/docker-flightradar24:latest-build-845
    container_name: fr24
    restart: unless-stopped
    ports:
      - 8754:8754
    networks:
      - adsb
    environment:
      - BEASTHOST=ultrafeeder
      - FR24KEY=${FR24_SHARING_KEY}
      - FR24KEY_UAT=${FR24_SHARING_KEY_UAT}
    tmpfs:
      - /var/log

networks:
  ingress:
  inference:
  adsb:

volumes:
  open-webui-data:
  litellm-db-data:
  ultrafeeder-globe-history:
  ultrafeeder-graphs1090:
