apiVersion: apps/v1
kind: Deployment

metadata:
  name: miniflux

spec:
  selector:
    matchLabels:
      app: miniflux
  replicas: 1
  template:
    metadata:
      labels:
        app: miniflux
    spec:
      containers:
        - name: miniflux
          image: ghcr.io/miniflux/miniflux:2.0.51
          imagePullPolicy: IfNotPresent

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-app
                  key: uri
            - name: RUN_MIGRATIONS
              value: "1"
            - name: BASE_URL
              value: https://miniflux.bootleg.technology

          # Uncomment the below lines to create the initial user
          # envFrom:
          #   - secretRef:
          #       name: admin-user

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /
              port: http

          readinessProbe:
            httpGet:
              path: /
              port: http
