apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: miniflux

resources:
  - namespace.yaml
  - postgres.yaml
  - admin_creds.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
