apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: miniflux

resources:
  - namespace.yaml
  - postgres.yaml
  - admin_creds.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/miniflux/miniflux
    newTag: 2.3.2-distroless@sha256:e2a2d2939d79687315385749c0ebcda0a1e8220e02c7e4f41f0e55cba2fbf1b7
