apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: miniflux

resources:
  - namespace.yaml
  - postgres.yaml
  - admin_creds.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/miniflux/miniflux
    newTag: 2.2.18-distroless@sha256:e60e2f8c2cdec6d3d24f533a0870233f5a30fba9258517f0ad5e95ffc9a35652
