apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true

  smartShutdownTimeout: 30

  postgresql:
    parameters:
      shared_buffers: "49MB"

  storage:
    size: 1Gi
    storageClass: nfs-csi
