apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true

  imageName: null
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 16

  postgresql:
    parameters:
      shared_buffers: "49MB"

  storage:
    size: 1Gi
    storageClass: nfs-csi

  resources:
    requests:
      memory: "196Mi"
    limits:
      memory: "196Mi"
