apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: calibre

resources:
  - namespace.yaml
  - persistent_volume_claim.yaml
  - deployment.yaml
  - service.yaml
  - middleware.yaml
  - ingress.yaml
