apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: pkg-fogo-sh
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/fogo-sh/pkg.fogo.sh.git
