- name: Add HashiCorp apt key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  become: yes

- name: Add HashiCorp repository
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ release_codename }} main"
    state: present
  become: yes

- name: Install Vault
  apt:
    name: vault
    update_cache: yes
  become: yes
