- package_facts:

- include_tasks: install.yml
  when: "'vault' not in packages"

- name: Write config
  template:
    src: "{{ role_path }}/templates/vault.hcl"
    dest: /etc/vault.d/vault.hcl
  become: yes
  notify:
    - Restart Vault

- name: Create Vault service
  copy:
    src: "{{ role_path }}/files/vault.service"
    dest: /usr/lib/systemd/system/vault.service
  become: yes

- name: Start & enable Vault
  systemd:
    name: vault
    state: started
    enabled: yes
  become: yes
  register: vault_start

- name: Skip restarting Vault
  set_fact:
    vault_skip_restart: "{{ vault_start.changed | bool }}"
