apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lgtm

resources:
  - namespace.yaml
  - helm_repositories.yaml
  - grafana.yaml
  - victoria_logs.yaml
  - prometheus_operator_crds.yaml
  - victoria_metrics_k8s_stack.yaml
