apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: riley+flux@rileyflynn.me
        name: Flux Image Update Automation
      messageTemplate: |
        Automated image update

        {{ range $filePath, $objectChanges := .Changed.FileChanges -}}
        {{ range $objID, $changes := $objectChanges -}}
        {{ range $change := $changes -}}
        - {{ $change.Setter }}: {{ $change.OldValue }} -> {{ $change.NewValue }}
        {{ end -}}
        {{ end -}}
        {{ end -}}
    push:
      branch: main
  update:
    path: ./flux/apps
    strategy: Setters
