apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: riley+flux@rileyflynn.me
        name: Flux Image Update Automation
      messageTemplate: |
        Automated image update

        {{ range $resource, $changes := .Changed.Objects -}}
        {{ $resource.Name }}: {{ range $_, $change := $changes }}{{ $change.OldValue }} -> {{ $change.NewValue }}{{ end }}
        {{ end }}
    push:
      branch: main
  update:
    path: ./flux/apps
    strategy: Setters
