- package_facts:

- include_tasks: install.yml
  when: "'nomad' not in packages"

- include_tasks: server.yml
  when: "nomad_role == 'server'"

- name: Write common config
  template:
    src: "{{ role_path }}/templates/nomad.hcl"
    dest: /etc/nomad.d/nomad.hcl
  become: yes
  notify:
    - Restart Nomad

- name: Write agent config
  template:
    src: "{{ role_path }}/templates/agent_config.hcl"
    dest: /etc/nomad.d/agent.hcl
  become: yes
  when: "nomad_role == 'agent'"
  notify:
    - Restart Nomad

- name: Create Nomad data directory
  file:
    path: /opt/nomad
    state: directory
    owner: nomad
    group: nomad
    mode: '0755'
  become: yes

- name: Create Nomad service
  copy:
    src: "{{ role_path }}/files/nomad.service"
    dest: /usr/lib/systemd/system/nomad.service
  become: yes

- name: Start & enable Nomad
  systemd:
    name: nomad
    state: started
    enabled: yes
  become: yes
  register: nomad_start

- name: Skip restarting Nomad
  set_fact:
    nomad_skip_restart: "{{ nomad_start.changed | bool }}"
