apiVersion: cert-manager.io/v1
kind: ClusterIssuer

metadata:
  name: letsencrypt-staging

spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: riley@rileyflynn.me
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: {{ required .Values.cloudflareSecretName "Value for 'cloudflareSecretName' is required" }}
              key: api-token
        selector:
          dnsZones:
            - internal.bootleg.technology
      - http01:
          ingress:
            ingressClassName: traefik
