- hosts: agents
  roles:
    - name: geerlingguy.docker
      become: yes

- hosts: all
  roles:
    - name: cloudalchemy.node-exporter
    - name: consul
    - role: oefenweb.dns
      become: yes
    - name: nomad

- hosts: controllers
  roles:
    - name: vault
