- hosts: agents
  roles:
    - role: geerlingguy.docker
      become: yes

- hosts: all
  roles:
    - role: oefenweb.dns
      become: yes
    - role: artis3n.tailscale
    - role: storage
      become: yes
    - role: cloudalchemy.node_exporter
    - role: patrickjahns.promtail
      # become: yes
    - role: consul
    - role: nomad
  post_tasks:
    - name: Fix DHCP config to stop overwriting nameservers
      lineinfile:
        regexp: "^#(.*)supersede domain-name-servers (.*);$"
        backrefs: true
        line: '\1supersede domain-name-servers \2;'
        dest: /etc/dhcp/dhclient.conf
        state: present
      become: yes
    - name: Run dhclient to apply updated settings
      command: dhclient
      become: yes
    - name: Install acl
      apt:
        name: acl
        state: present
      become: yes
    - name: Configure Docker ACL
      command: setfacl -R -m u:promtail:rwx /var/lib/docker/containers
      become: yes
    - name: Restart promtail
      systemd:
        name: promtail
        state: restarted
      become: yes

- hosts: controllers
  roles:
    - role: vault

- hosts: all
  serial: 1
  tasks:
    - systemd:
        name: tailscaled
        state: restarted
      become: yes
