- hosts: agents
  roles:
    - role: geerlingguy.docker
      become: yes

- hosts: all
  roles:
    - role: artis3n.tailscale
    - role: cloudalchemy.node-exporter
    - role: consul
    - role: oefenweb.dns
      become: yes
    - role: nomad

- hosts: controllers
  roles:
    - role: vault
