all:
  children:
    controllers:
      hosts:
        192.168.1.6:
        192.168.1.252:
        192.168.1.183:
      vars:
        consul_role: server
        nomad_role: server
        dns_nameservers:
          - 127.0.0.1
        tailscale_args: --accept-dns=false --accept-routes
    agents:
      hosts:
        192.168.1.129:
        143.110.217.224:
          is_cloud: true
      vars:
        consul_role: agent
        nomad_role: agent
        dns_nameservers:
          - 8.8.8.8
          - 8.8.4.4
        tailscale_args: --accept-dns=true --accept-routes
  vars:
    ansible_user: debian
    consul_servers:
      - 100.71.98.21
      - 100.73.241.83
      - 100.125.202.69
    consul_datacenter_name: hera
    nomad_datacenter_name: hera
    consul_domain_name: "bootleg.technology."
    unbound_permitted_cidr_blocks:
      - 192.168.1.0/24
      - 172.17.0.1/16
      - 100.0.0.0/8
    internal_tools_ip: 100.99.237.85
    tailscale_auth_key: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      34343963613033633632313864326634333234333138323131313731393436346366363463643166
      3038623932333138353365376132383261303836303232630a346438363234613331353836363137
      38666564373430386533306661393932353363343166393165303863326239656539363932353839
      3661353638626566370a653830663033366437306234356535326236316366663434643965656538
      31333562373736393763303331653266313162653230393966303761393731653664
    dns_dhclient_rules:
      domain-name:
        rule: supersede
      domain-name-servers:
        rule: supersede
      domain-search:
        rule: supersede
    nas_ip_address: 192.168.1.106
    nas_src_path: /mnt/Storage/iocage/cluster
    promtail_loki_server_url: http://loki.internal.bootleg.technology
    promtail_config_scrape_configs:
      - job_name: system
        static_configs:
          - targets:
              - localhost
            labels:
              job: varlogs
              __path__: /var/log/*log

      - job_name: containers
        static_configs:
          - targets:
              - localhost
            labels:
              job: containerlogs
              __path__: /var/lib/docker/containers/*/*log

        # pipeline_stages:
        #   - json:
        #       expressions:
        #         output: log
        #         stream: stream
        #         attrs:
        #   - json:
        #       expressions:
        #         tag:
        #       source: attrs
        #   - regex:
        #       expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
        #       source: tag
        #   - timestamp:
        #       format: RFC3339Nano
        #       source: time
        #   - labels:
        #       tag:
        #       stream:
        #       image_name:
        #       container_name:
        #       image_id:
        #       container_id:
        #   - output:
        #       source: output
