all:
  children:
    controllers:
      hosts:
        192.168.2.35:
        192.168.2.36:
        192.168.2.37:
      vars:
        consul_role: server
  vars:
    ansible_user: debian
    consul_servers:
      - 192.168.2.35
      - 192.168.2.36
      - 192.168.2.37
    consul_datacenter_name: hera
    consul_domain_name: "bootleg.technology."
