all:
  children:
    controllers:
      hosts:
        192.168.2.35:
        192.168.2.36:
        192.168.2.37:
      vars:
        consul_role: server
        consul_servers:
          - 192.168.2.35
          - 192.168.2.36
          - 192.168.2.37
  vars:
    ansible_user: debian
