apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - persistent_volume_claim.yaml
  - config.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - image_repository.yaml
  - image_policy.yaml
images:
  - name: ghcr.io/nint8835/skyline
    newTag: main-2c5442f-20260726-110637 # {"$imagepolicy": "flux-system:skyline:tag"}
    digest: sha256:7d66e202fda33ce8c1b24a71cb54899f54776f7d78fee0fa821a77ce401cdf75 # {"$imagepolicy": "flux-system:skyline:digest"}
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: override-namespace
      namespace: skyline
    unsetOnly: true
