apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netbox

resources:
  - namespace.yaml
  - postgres.yaml
  - persistent_volume_claim.yaml
  - redis.yaml
  - service_redis.yaml
  - config.yaml
  - secrets.yaml
  - netbox.yaml
  - service_netbox.yaml
  - netbox_worker.yaml
  - ingress.yaml

configMapGenerator:
  - name: config-dir
    files:
      - config/configuration.py
      - config/extra.py
      - config/logging.py
      - config/plugins.py

images:
  - name: ghcr.io/netbox-community/netbox
    newTag: v4.5.10@sha256:3b053a0bd29d8a91e240bfe672d001d8e679b31cf0bea30f9c079fc76bdc1e54
  - name: ghcr.io/valkey-io/valkey
    newTag: 9.0.4-alpine@sha256:d1cc70645bbcef743615463a2fa4616e841407545e18f560aed0c49671a90147
