apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netbox

resources:
  - namespace.yaml
  - postgres.yaml
  - persistent_volume_claim.yaml
  - redis.yaml
  - service_redis.yaml
  - config.yaml
  - secrets.yaml
  - netbox.yaml
  - service_netbox.yaml
  - netbox_worker.yaml
  - ingress.yaml

configMapGenerator:
  - name: config-dir
    files:
      - config/configuration.py
      - config/extra.py
      - config/logging.py
      - config/plugins.py

images:
  - name: ghcr.io/netbox-community/netbox
    newTag: v4.6.3@sha256:f1c91ad06d3e5f0aadb9cf0b44f1a9dc83646f95afe9b79f78bde33dead728a3
  - name: ghcr.io/valkey-io/valkey
    newTag: 9.1.0-alpine@sha256:a35428eba9043cc0b79dbe54100f0c92784f2de00ad09b01182bfb1c5c83d1bd
