apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netbox

resources:
  - namespace.yaml
  - postgres.yaml
  - persistent_volume_claim.yaml
  - redis.yaml
  - service_redis.yaml
  - config.yaml
  - secrets.yaml
  - netbox.yaml
  - service_netbox.yaml
  - netbox_worker.yaml
  - ingress.yaml

configMapGenerator:
  - name: config-dir
    files:
      - config/configuration.py
      - config/extra.py
      - config/logging.py
      - config/plugins.py

images:
  - name: ghcr.io/netbox-community/netbox
    newTag: v4.5.9@sha256:4b442a0143135f84536ae2eb9e2b71b853e357b82ae4209544a13167c4bb3949
  - name: ghcr.io/valkey-io/valkey
    newTag: 9.0.3-alpine@sha256:84c96f47ebe197e635cd3ddbe3ab74e8bdf783cf3befbfb1c36387275c1cd5d5
