apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - persistent_volume_claim.yaml
  - config.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - image_repository.yaml
  - image_policy.yaml
images:
  - name: ghcr.io/nint8835/pollster
    newTag: main-c9804dd-20260712-205400 # {"$imagepolicy": "flux-system:pollster:tag"}
    digest: sha256:63312f6ef69813db84dc81dd7d20fd1359d8ce6618f7e354924743eaaf11b0b6 # {"$imagepolicy": "flux-system:pollster:digest"}
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: override-namespace
      namespace: pollster
    unsetOnly: true
