apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopkeeper

spec:
  selector:
    matchLabels:
      app: shopkeeper

  template:
    metadata:
      labels:
        app: shopkeeper

    spec:
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: database

      containers:
        - name: shopkeeper
          image: ghcr.io/nint8835/shopkeeper:latest
          imagePullPolicy: Always
          args: [ "start" ]

          envFrom:
            - secretRef:
                name: config
              prefix: SHOPKEEPER_
          volumeMounts:
            - mountPath: /data
              name: database

      initContainers:
        - name: upgrade-db
          image: ghcr.io/nint8835/shopkeeper:latest
          imagePullPolicy: Always
          args: [ "upgrade" ]
          envFrom:
            - secretRef:
                name: config
              prefix: SHOPKEEPER_
          volumeMounts:
            - mountPath: /data
              name: database

        - name: sync-commands
          image: ghcr.io/nint8835/shopkeeper:latest
          imagePullPolicy: Always
          args: [ "sync" ]
          envFrom:
            - secretRef:
                name: config
              prefix: SHOPKEEPER_
      