apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - persistent_volume_claim.yaml
  - config.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - image_repository.yaml
  - image_policy.yaml
images:
  - name: ghcr.io/nint8835/shopkeeper
    newTag: main-b3ccfcf-20260412-165057 # {"$imagepolicy": "flux-system:shopkeeper:tag"}
    digest: sha256:24b464ab87385c1554fb7cc50afced5d22fc647b83277215934a8b5151aaeb71 # {"$imagepolicy": "flux-system:shopkeeper:digest"}
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: override-namespace
      namespace: shopkeeper
    unsetOnly: true
