apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - persistent_volume_claim.yaml
  - config.yaml
  - secrets.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - image_repository.yaml
  - image_policy.yaml
images:
  - name: ghcr.io/nint8835/shopkeeper
    newTag: main-4ee9b71-20260712-212804 # {"$imagepolicy": "flux-system:shopkeeper:tag"}
    digest: sha256:04110bcbc172797b91fbe0199189ee7cf009d206d9f21059f02ba21fbfb3c7db # {"$imagepolicy": "flux-system:shopkeeper:digest"}
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: override-namespace
      namespace: shopkeeper
    unsetOnly: true
