site_name: ops.bootleg.technology
docs_dir: content
repo_url: https://github.com/nint8835/ops
repo_name: nint8835/ops
edit_uri: edit/main/docs/content/
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: teal
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    logo: material/server
    repo: material/github
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
plugins:
  - search
extra:
  social:
    - icon: material/twitter
      link: https://twitter.com/bootlegjohn
    - icon: material/github
      link: https://github.com/nint8835
copyright: Copyright &copy; 2022 Riley Flynn

nav:
  - index.md
  - Guides:
    - Cluster Maintenance:
      - guides/cluster-maintenance/cluster-setup.md
      - guides/cluster-maintenance/adding-a-node.md
