apiVersion: postgresql.cnpg.io/v1
kind: Database

metadata:
  name: app

spec:
  name: app
  owner: app

  cluster:
    name: db
  
  extensions:
    - name: vector
      # renovate: suite=trixie-pgdg depName=postgresql-18-pgvector extractVersion=^(?<version>\d+\.\d+\.\d+)
      version: '0.8.6'
