apiVersion: postgresql.cnpg.io/v1
kind: Database

metadata:
  name: app

spec:
  name: app
  owner: app

  cluster:
    name: db
  
  extensions:
    - name: uuid-ossp
      ensure: present
    - name: pg_trgm
      ensure: present
    - name: unaccent
      ensure: present
    - name: vector
      # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/pgvector extractVersion=^(?<version>\d+\.\d+\.\d+)-18-trixie$ versioning=semver
      version: '0.8.6'
