apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookorbit

resources:
  - namespace.yaml
  - database_cluster.yaml
  - database.yaml
  - persistent_volume_claim.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

secretGenerator:
  - name: secrets
    envs:
      - secrets.env

images:
  - name: ghcr.io/bookorbit/bookorbit
    newTag: 3.0.0@sha256:571ea47b036a8b371db9c54d54a3cea0fb96245f66c09584efac799afd339716
