apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookorbit

resources:
  - namespace.yaml
  - database_cluster.yaml
  - database.yaml
  - persistent_volume_claim.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

secretGenerator:
  - name: secrets
    envs:
      - secrets.env

images:
  - name: ghcr.io/bookorbit/bookorbit
    newTag: 3.1.0@sha256:78b6eac18306eb7eba0dbf6592ecdee01b15f24de9a941cb853db4a0232d7999
