apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookorbit

resources:
  - namespace.yaml
  - database_cluster.yaml
  - database.yaml
  - persistent_volume_claim.yaml
  - secrets.yaml
  - deployment.yaml

images:
  - name: ghcr.io/bookorbit/bookorbit
    newTag: 2.7.0sha256:0f46241c54ba7cd07ddf7dc519386a29c98dd0f3679cebc9ca35f3305dc79e69
