apiVersion: v1
kind: Secret
metadata:
    name: secrets
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:IBp5AxXQZ457m/FB4oYVRtc4vuaq9K/5HFIoLUeXFI2FihuE/oh9/PyXxNfV8GqRjq2b/Qyb6m9r8X8EFZdGgQ==,iv:MawVovz+HH4NNjFL5V5XDHcC/oZ/mop8CsrNDvlNc7Y=,tag:iKd5iHU7YPzsCg5zv67KOA==,type:str]
    SETUP_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:Ht46bsXRWeEA9ZuP5elPGa6QFvIuoDlbhcuGwAy4bOCK+g+YLuGqRBCntW5fTxQ0l2Ffv+YB8qhe5UpvyGBPWw==,iv:XbvXDG4A7Gf0QgNWL3f74qqs3O8MQcORZK7JQPXbpNE=,tag:KvJcGkborGTVj7kL0ze25g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQVRHQm1xVmdlN1Y1MU1W
            U3lhZjFsaklaaFdnc0hqRFJwWnA1Umh0L0RJClFHVHg0MllDUVJqYTFIa2NheVVv
            Vkg5M1ZOYjlrdmxyam5CWTJFdWxhQ3cKLS0tIDIyS2l3QzBteE5CbG95RnZCKzBr
            c0lEalNnczFZcU5EYmtTMStmWnJsZXMKI4aPmmNEOuYREileGj7UkM8X+/pdbq9I
            1u4poA+sdpOFYT9GuJ6I1IEeQQUsxg8qQhnqhfwmlYHdQAdOhl2ZBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rmn09vuxjzh9wmx4hj8zz72ckgaa3psdzsaglj3all5k7gp5wqpsvvtmz7
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-23T02:15:33Z"
    mac: ENC[AES256_GCM,data:e/I0okgxPR+xudrMdQ9moGwiAD030o1Iiu0X8Fey1qSOW8TCC+7+Grljvj6NPCqbqjh/+FVarNG+f/ExsnQ2uIQA6ivurNRTQaHfIalk0rdyBu2hUQC+a9o209RcZAUlxJYprO1PIoLxxnu/5goXAVWqaK3XPuYIyvUW1Nsxcg8=,iv:d1qXKuFtJc6IdTgz/eRKkFoA7l1D2AIFtBq2iJfzdcA=,tag:ijS6d0yCJHp5ZrebHkM3Aw==,type:str]
    version: 3.13.3
