apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: loki-stack
spec:
  interval: 1h
  chart:
    spec:
      chart: loki-stack
      version: "2.6.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    grafana:
      enabled: true
      persistence:
        enabled: true
        storageClassName: longhorn
        size: 1Gi
    prometheus:
      enabled: true
      alertmanager:
        persistentVolume:
          storageClass: longhorn
          size: 1Gi
      server:
        persistentVolume:
          storageClass: longhorn
          size: 5Gi
    loki:
      persistence:
        enabled: true
        storageClassName: longhorn
        size: 5Gi
