apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository

metadata:
  name: ntv-webcam-scraper
  namespace: flux-system

spec:
  image: ghcr.io/nint8835/ntv-webcam-scraper
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy

metadata:
  name: ntv-webcam-scraper
  namespace: flux-system

spec:
  imageRepositoryRef:
    name: ntv-webcam-scraper
  filterTags:
    pattern: '^main-[[:xdigit:]]{7,}-(?P<ts>\d{8}-\d{6})$'
    extract: '$ts'
  policy:
    alphabetical:
      order: asc
  digestReflectionPolicy: IfNotPresent
