name: Lint Actions

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
  pull_request:
    paths:
      - .github/workflows/**

permissions:
  contents: read
  security-events: write

jobs:
  lint-actions:
    uses: nint8835/workflows/.github/workflows/lint-actions.yaml@main
