name: Lint Actions

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
  pull_request:
    paths:
      - .github/workflows/**

permissions: {}

jobs:
  lint-actions:
    uses: nint8835/workflows/.github/workflows/lint-actions.yaml@main
    permissions:
      actions: read # Needed to read GitHub Actions information
      contents: read # Needed to clone the repository
      security-events: write # Needed to submit scan results to GitHub
