theme:
  background-color: 0 0 13
  primary-color: 343 96 68

branding:
  hide-footer: true

pages:
  - name: Home
    width: slim
    hide-desktop-navigation: true
    center-vertically: true

    columns:
      - size: full
        widgets:
          - type: search
            autofocus: true

          - type: calendar

          - type: weather
            location: St. John's, Canada
