apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: glance

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: config
    files:
      - config.yaml
